### ISSUE TITLE
South data migration does not work well with django-simple-history

### ISSUE THREAD

**Issue by KennethVerbeure** [matthiask/south#2]
when adding/changing data to fields of a model in a south data migration and after saving the model, no new history record is created in the database.

After my migration i expect a new history record to be added in the database. However all i see is that my normal model is updated with the new data, but no new history record is made for that.

im using the orm parameter provided in the forwards function

I noticed on the django-simple-history repo that they attach a history to a model when the django 'class-prepared' signal is triggered for that model class. Then they attach handlers to the django save signal. All of this is not happening when working with the orm parameter.

where all the simple-history magic happens: https://github.com/treyhunner/django-simple-history/blob/master/simple_history/models.py#L50

i am using south 0.8.4

**Comment by matthiask** [comment]
Thanks for the report. The official south repository is here: https://bitbucket.org/andrewgodwin/south/src
